"""Stable public contract for cross-format document structure."""

from .interfaces import ManifestConsumer, StructureScanner
from .capabilities import (
    CapabilityDecision,
    FormatCapability,
    ModeCapability,
    RequirementLevel,
    RuntimeFeature,
    RuntimeState,
    all_format_capabilities,
    capability_for,
    source_format_for_extension,
    source_formats_for_mime,
)
from .models import (
    CURRENT_SCHEMA_VERSION,
    AssetRef,
    AssetRole,
    BodyObject,
    BoundingBox,
    Canvas,
    CanvasKind,
    CaptionObject,
    ContentProfile,
    CoordinateUnit,
    DetectorEvidence,
    DocumentInfo,
    DocumentStructureManifest,
    ExecutionStatus,
    FigureObject,
    ImageObject,
    IssueSeverity,
    LayoutMode,
    ManifestIssue,
    ManifestSummary,
    ObjectType,
    OutputEditability,
    PipelineStage,
    PosterSectionObject,
    ProcessingMode,
    ProducerInfo,
    ProfileSource,
    Representation,
    SemanticObject,
    ShapeObject,
    SourceFormat,
    SourceGeometry,
    SourceRef,
    SourceRefKind,
    TableObject,
    TextBoxObject,
    TranslatableBlock,
    build_manifest_id,
    build_object_id,
)
from .profiles import (
    ProfileDecision,
    ProfileSpec,
    ReadingStrategy,
    all_content_profiles,
    profile_for,
    resolve_profile,
)
from .ingest import (
    DEFAULT_MAX_UPLOAD_BYTES,
    DetectedInput,
    InputPreparationError,
    PreparedDocument,
    detect_input,
    prepare_document,
    sanitize_upload_name,
    workflow_for_source_format,
)
from .runtime import (
    FeatureProbe,
    RuntimeCapabilitySnapshot,
    decide_runtime_capability,
    probe_runtime_capabilities,
)
from .canvases import CanvasLimits, extract_canvases
from .manifest_store import ManifestStore, default_cache_root
from .captions import (
    CAPTION_LINE,
    FIGURE_LINE,
    caption_anchors,
    figure_caption_num,
    is_continued_caption,
    is_toc_line,
    squeeze_caps,
    table_caption_num,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "CapabilityDecision",
    "AssetRef",
    "AssetRole",
    "BodyObject",
    "BoundingBox",
    "Canvas",
    "CanvasKind",
    "CaptionObject",
    "ContentProfile",
    "CoordinateUnit",
    "DetectorEvidence",
    "DocumentInfo",
    "DocumentStructureManifest",
    "ExecutionStatus",
    "FigureObject",
    "FormatCapability",
    "ImageObject",
    "IssueSeverity",
    "LayoutMode",
    "ManifestConsumer",
    "ManifestIssue",
    "ManifestSummary",
    "ModeCapability",
    "ObjectType",
    "OutputEditability",
    "PipelineStage",
    "PosterSectionObject",
    "ProcessingMode",
    "ProducerInfo",
    "ProfileSource",
    "ProfileDecision",
    "ProfileSpec",
    "ReadingStrategy",
    "Representation",
    "RequirementLevel",
    "RuntimeFeature",
    "RuntimeState",
    "SemanticObject",
    "ShapeObject",
    "SourceFormat",
    "SourceGeometry",
    "SourceRef",
    "SourceRefKind",
    "StructureScanner",
    "TableObject",
    "TextBoxObject",
    "TranslatableBlock",
    "build_manifest_id",
    "build_object_id",
    "all_format_capabilities",
    "capability_for",
    "source_format_for_extension",
    "source_formats_for_mime",
    "all_content_profiles",
    "profile_for",
    "resolve_profile",
    "DEFAULT_MAX_UPLOAD_BYTES",
    "DetectedInput",
    "InputPreparationError",
    "PreparedDocument",
    "detect_input",
    "prepare_document",
    "sanitize_upload_name",
    "workflow_for_source_format",
    "FeatureProbe",
    "RuntimeCapabilitySnapshot",
    "decide_runtime_capability",
    "probe_runtime_capabilities",
    "CanvasLimits",
    "ManifestStore",
    "PdfStructureScanner",
    "DocxStructureScanner",
    "ImageStructureScanner",
    "PptxStructureScanner",
    "default_cache_root",
    "extract_canvases",
    "CAPTION_LINE",
    "FIGURE_LINE",
    "caption_anchors",
    "figure_caption_num",
    "is_continued_caption",
    "is_toc_line",
    "squeeze_caps",
    "table_caption_num",
]

_LAZY_EXPORTS = {
    "PdfStructureScanner": ("scan_pdf", "PdfStructureScanner"),
    "DocxStructureScanner": ("scan_docx", "DocxStructureScanner"),
    "ImageStructureScanner": ("scan_image", "ImageStructureScanner"),
    "PptxStructureScanner": ("scan_pptx", "PptxStructureScanner"),
}


def __getattr__(name: str):
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = _LAZY_EXPORTS[name]
    from importlib import import_module

    module = import_module(f".{module_name}", __name__)
    return getattr(module, attr)
